import {
  Product,
  Category,
  StorefrontTheme,
  CustomDomainConfig,
  Automation,
  Customer,
  Conversation,
  Order,
  PaymentGatewayConfig,
  InstagramAccountState,
  SocialChannelAccount,
  ChannelCapability,
  ChannelAnalyticsData,
  PerformanceSlice,
  DailyDMData,
  KeywordMetric,
  LogEntry,
  ActivityItem
} from './types';

// ==========================================
// MULTI-CHANNEL CAPABILITIES & ACCOUNTS
// ==========================================

export const CHANNEL_CAPABILITIES_CONFIG: Record<string, ChannelCapability> = {
  instagram: {
    channel: 'instagram',
    name: 'Instagram',
    comments: true,
    dm: true,
    keywordTrigger: true,
    postBasedAutomation: true,
    templates: false,
    commands: false,
    webhooks: true,
    statusNotice: 'Meta Graph API v19.0 verified. Supports comment webhooks and private direct replies.',
  },
  tiktok: {
    channel: 'tiktok',
    name: 'TikTok',
    comments: 'configurable',
    dm: 'configurable',
    keywordTrigger: 'configurable',
    postBasedAutomation: true,
    templates: false,
    commands: false,
    webhooks: true,
    statusNotice: 'TikTok Open API connected. Direct messaging requires approved partner permissions; comment monitoring active.',
  },
  whatsapp: {
    channel: 'whatsapp',
    name: 'WhatsApp Business',
    comments: false,
    dm: true,
    keywordTrigger: true,
    templates: true,
    commands: false,
    webhooks: true,
    statusNotice: 'Official Meta Cloud API. Supports pre-approved templates, 24h service window, and catalog links.',
  },
  telegram: {
    channel: 'telegram',
    name: 'Telegram',
    comments: false,
    dm: true,
    keywordTrigger: true,
    templates: false,
    commands: true,
    webhooks: true,
    statusNotice: 'Telegram Bot API connected. High rate limits, instant bot commands (/buy, /catalog), and inline buttons.',
  },
};

export const INITIAL_SOCIAL_CHANNELS: SocialChannelAccount[] = [
  {
    id: 'chan-ig-1',
    channel: 'instagram',
    accountName: 'Mridalini Official (Business)',
    handle: '@mridaliniofficial',
    profileImage: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=500&auto=format&fit=crop&q=80',
    isConnected: true,
    status: 'active',
    channelTypeLabel: 'Instagram Business (Graph API v21.0)',
    lastSync: 'Live (Graph API Connected)',
    webhookStatus: 'operational',
    webhookUrl: '/api/webhook/instagram',
    capabilities: CHANNEL_CAPABILITIES_CONFIG.instagram,
    metrics: {
      followers: 12400,
      messagesReceived: 842,
      conversions: 148,
    },
    credentialsHint: 'Connected via Meta App ID: 1097121733196692 (Account ID: 28503726299236968)',
  },
  {
    id: 'chan-tt-1',
    channel: 'tiktok',
    accountName: 'Ankit Tech & Builds',
    handle: '@ankit_tech',
    profileImage: '/src/assets/images/avatar_ankit_1790498690280.jpg',
    isConnected: true,
    status: 'active',
    channelTypeLabel: 'TikTok Creator Account',
    lastSync: '14 mins ago',
    webhookStatus: 'operational',
    webhookUrl: 'https://api.autodm.com/webhooks/v1/tiktok',
    capabilities: CHANNEL_CAPABILITIES_CONFIG.tiktok,
    metrics: {
      followers: 92400,
      messagesReceived: 950,
      conversions: 142,
    },
    credentialsHint: 'TikTok Open API (App ID: 73928192048)',
  },
  {
    id: 'chan-wa-1',
    channel: 'whatsapp',
    accountName: 'AutoDM Store Concierge',
    handle: '+91 98765 43210',
    profileImage: '/src/assets/images/avatar_sarah_1790499318738.jpg',
    isConnected: true,
    status: 'active',
    channelTypeLabel: 'WhatsApp Business Cloud API',
    lastSync: 'Just now',
    webhookStatus: 'operational',
    webhookUrl: 'https://api.autodm.com/webhooks/v1/whatsapp',
    capabilities: CHANNEL_CAPABILITIES_CONFIG.whatsapp,
    metrics: {
      messagesReceived: 620,
      conversions: 94,
    },
    credentialsHint: 'WABA ID: 94810294819 | Meta Verified Phone',
  },
  {
    id: 'chan-tg-1',
    channel: 'telegram',
    accountName: 'AutoDM Store VIP Bot',
    handle: '@AutoDM_AnkitBot',
    profileImage: '/src/assets/images/digital_product_1790499336046.jpg',
    isConnected: true,
    status: 'active',
    channelTypeLabel: 'Telegram Bot API',
    lastSync: '1 min ago',
    webhookStatus: 'operational',
    webhookUrl: 'https://api.autodm.com/webhooks/v1/telegram',
    capabilities: CHANNEL_CAPABILITIES_CONFIG.telegram,
    metrics: {
      subscribers: 14200,
      messagesReceived: 480,
      conversions: 51,
    },
    credentialsHint: 'Bot Token: 719284****:AAH9...',
  },
];

export const INITIAL_INSTAGRAM_ACCOUNT: InstagramAccountState = {
  handle: 'mridaliniofficial',
  name: 'Mridalini Official',
  businessName: 'Mridalini Official',
  category: 'Fashion & Retail',
  accountType: 'Business',
  isConnected: true,
  avatarUrl: 'https://scontent-tpe1-1.cdninstagram.com/v/t51.82787-19/751206463_18202213531329609_2979703026788183658_n.jpg?stp=dst-jpg_s206x206_tt6&_nc_cat=106&ccb=7-5&_nc_sid=bf7eb4&efg=eyJ2ZW5jb2RlX3RhZyI6InByb2ZpbGVfcGljLnd3dy43MzUuQzMifQ%3D%3D&_nc_ohc=1iTBTT2cCVMQ7kNvwHhVxPx&_nc_oc=AdpbeMGUNaoWMf1vtJkvK0nrDV869KqyfUJEFUtHS-hziAQec54XJ78wL0uI_eyP9xodbvfMDhDPfIhIyJ2Jc--h&_nc_zt=24&_nc_ht=scontent-tpe1-1.cdninstagram.com&edm=AP4hL3IEAAAA&_nc_gid=-ofZrpsEuBGWhfNnZOFxjA&_nc_tpa=Q5bMBQIcDoLaz2pPFwul3NxYYkPMXgmpsgRNzIZyFBgd8vYS7HE_HPjBipkl_zMtaqUnYYr7sWhUWPvgGA&oh=00_AQNKN382gsABtREPVFPXJRoQRQ-nzkIAgxz6wa_MPs9Crw&oe=6AC0A40B',
  followers: 12400,
  postsCount: 5,
  apiHealth: '100% Operational (Live Meta Graph API)',
  webhookActive: true,
  lastSyncedAt: 'Live via Meta Graph API',
  connectedSince: 'Meta Connected',
  deliveryRate: '100%',
};

export const INITIAL_CATEGORIES: Category[] = [
  { id: 'cat-1', name: 'Festive Ensembles & Kurta Sets', slug: 'festive-ensembles', productCount: 2, order: 1 },
  { id: 'cat-2', name: 'Designer Dupattas & Stoles', slug: 'dupattas-stoles', productCount: 1, order: 2 },
  { id: 'cat-3', name: 'Luxe Occasion Wear', slug: 'occasion-wear', productCount: 1, order: 3 },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-1',
    title: 'Mridalini Signature Embroidered Kurta Set',
    slug: 'mridalini-signature-kurta-set',
    type: 'physical',
    description: 'Bespoke hand-embroidered festive kurta set featuring intricate zardozi detailing, crafted in pure chanderi silk with matching pants and organza dupatta.',
    price: 79,
    compareAtPrice: 119,
    images: ['https://scontent-tpe1-1.cdninstagram.com/v/t51.71878-15/758400594_1074641168558022_1484593028835977962_n.jpg?stp=dst-jpg_e35_tt6&_nc_cat=106&ccb=7-5&_nc_sid=a54f6b&efg=eyJlZmdfdGFnIjoiYmVzdF9pbWFnZV91cmxnZW4uQ0xJUFMuQzMifQ%3D%3D&_nc_ohc=HVabN2FWD9oQ7kNvwFM9FBh&_nc_oc=AdoP2Bf2hCiK3OAEETclYPi9L9VgUDxABn71tcLNI0MORMe1y1HOucbGZiNFCAABwHgqnL4umtwQvnzhrNFuOo1c&_nc_zt=23&_nc_ht=scontent-tpe1-1.cdninstagram.com&edm=ANo9K5cEAAAA&_nc_gid=QtKzGqASPYGF0NL_5VfPVA&_nc_tpa=Q5bMBQLk8FizTLNX151tK6mV209F174oTBZUa2rPNQc4Hn82y_MIhwf4FvvS5LLXgF8eSfd7z28Gxuvjrg&oh=00_AQOm2l9bXA6nStQi0kisLsse273EDDqCS5zrbE2spawy_A&oe=6AC085D9'],
    categoryId: 'cat-1',
    categoryName: 'Festive Ensembles & Kurta Sets',
    status: 'active',
    sku: 'MRID-SET-01',
    stock: 25,
    variants: [
      { id: 'var-1', name: 'Emerald Green (S/M)', price: 79, stock: 15 },
      { id: 'var-2', name: 'Royal Crimson (L/XL)', price: 84, stock: 10 },
    ],
    views: 1840,
    clicks: 920,
    addToCartCount: 340,
    ordersCount: 98,
    revenue: 7742,
  },
  {
    id: 'prod-2',
    title: 'Handcrafted Pure Silk Anarkali Gown',
    slug: 'pure-silk-anarkali-gown',
    type: 'physical',
    description: 'Floor-length pure banarasi silk anarkali gown adorned with handwoven gold motifs and scalloped border dupatta.',
    price: 129,
    compareAtPrice: 189,
    images: ['https://scontent-tpe1-1.cdninstagram.com/v/t51.82787-15/759408922_18203433670329609_4651465586871677850_n.webp?stp=dst-jpg_e35_tt6&_nc_cat=105&ig_cache_key=Mzk1MDcyNDU4MjEzMDQ3MTc1Mw%3D%3D.3-ccb7-5&ccb=7-5&_nc_sid=a54f6b&efg=eyJlZmdfdGFnIjoiYmVzdF9pbWFnZV91cmxnZW4uRkVFRC5DMyJ9&_nc_ohc=8mFyUENJVCIQ7kNvwE2AhgJ&_nc_oc=AdqW_pUytybg9Kdo_sowbA97rdt6Uyn2a23woREP0K-sBhhV7XC3cSKE87waGrLdV3_vlfaigdjus9r1CQfjtul5&_nc_zt=23&_nc_ht=scontent-tpe1-1.cdninstagram.com&edm=ANo9K5cEAAAA&_nc_gid=QtKzGqASPYGF0NL_5VfPVA&_nc_tpa=Q5bMBQK_gVaz89JQXX5TPHjjcC5CtJIOIWI5v0q1mk8EvzELJTIGJvLvKTPUkGGeGAhCVX291OOaXdoWdA&oh=00_AQMfDU3Gh7HFfLZsBYxxfOeqis05_FN3boTb2jfsp2pC7Q&oe=6AC09EEF'],
    categoryId: 'cat-3',
    categoryName: 'Luxe Occasion Wear',
    status: 'active',
    sku: 'MRID-SILK-02',
    stock: 14,
    variants: [
      { id: 'var-3', name: 'Opal Ivory', price: 129, stock: 8 },
      { id: 'var-4', name: 'Blush Rose', price: 135, stock: 6 },
    ],
    views: 1420,
    clicks: 780,
    addToCartCount: 220,
    ordersCount: 64,
    revenue: 8256,
  },
  {
    id: 'prod-3',
    title: 'Artisanal Zari Bordered Tissue Stole',
    slug: 'zari-bordered-tissue-stole',
    type: 'physical',
    description: 'Lightweight metallic tissue stole finished with antique gold zari fringes. Elevates any celebratory outfit with subtle sheen.',
    price: 39,
    compareAtPrice: 59,
    images: ['https://scontent-tpe1-1.cdninstagram.com/v/t51.82787-15/757954711_18203430457329609_9017753783645031254_n.webp?stp=dst-jpg_e35_tt6&_nc_cat=107&ig_cache_key=Mzk1MDcxODAyOTMwMjEwNjc0OQ%3D%3D.3-ccb7-5&ccb=7-5&_nc_sid=a54f6b&efg=eyJlZmdfdGFnIjoiYmVzdF9pbWFnZV91cmxnZW4uRkVFRC5DMyJ9&_nc_ohc=PZ6JxjyCOIMQ7kNvwHbKImY&_nc_oc=AdpSGnm8N4gVVfSvCXbvfKwmwbxhOjGOc2qgOAgYnn_owlaExFMNwlXy5en-mbZi48_4ZqJBbJmwkjmFHsDDYivD&_nc_zt=23&_nc_ht=scontent-tpe1-1.cdninstagram.com&edm=ANo9K5cEAAAA&_nc_gid=QtKzGqASPYGF0NL_5VfPVA&_nc_tpa=Q5bMBQLVIucMKNhf8xc_F5Fu2KB2nB03DdoJK_3-twvUMmmQ7zUH7TSdusD1BfBP4a-etgVkOo1sqLqJYw&oh=00_AQOzXGrS1hjbNVT5gMe3FChLf42tCl9_7-cb6vY-qFRapg&oe=6AC07DC2'],
    categoryId: 'cat-2',
    categoryName: 'Designer Dupattas & Stoles',
    status: 'active',
    sku: 'MRID-STOLE-03',
    stock: 40,
    views: 1210,
    clicks: 650,
    addToCartCount: 290,
    ordersCount: 112,
    revenue: 4368,
  },
  {
    id: 'prod-4',
    title: 'Royal Velvet Kurta with Resham Embroidery',
    slug: 'royal-velvet-kurta',
    type: 'physical',
    description: 'Micro-velvet straight cut kurta with tonal resham floral vines and pocket detailing. Ideal for winter celebrations.',
    price: 99,
    compareAtPrice: 149,
    images: ['https://scontent-tpe1-1.cdninstagram.com/v/t51.82787-15/757656953_18203430388329609_9134546905843078551_n.webp?stp=dst-jpg_e35_tt6&_nc_cat=104&ig_cache_key=Mzk1MDcxNzgwMDkzMDY1ODgwMw%3D%3D.3-ccb7-5&ccb=7-5&_nc_sid=a54f6b&efg=eyJlZmdfdGFnIjoiYmVzdF9pbWFnZV91cmxnZW4uRkVFRC5DMyJ9&_nc_ohc=CRNZ2vILwuEQ7kNvwHRJ_l0&_nc_oc=AdpNcvdy2FYqE4umgbP-8OKwPs4K91RLfF3tWkwXxBKJLxyo7J86xKlKAnMif66U5V5nvWxy6RtbV-5g3eTcLLZ8&_nc_zt=23&_nc_ht=scontent-tpe1-1.cdninstagram.com&edm=ANo9K5cEAAAA&_nc_gid=QtKzGqASPYGF0NL_5VfPVA&_nc_tpa=Q5bMBQJmKoW59rIXiSaQKgNT-sPQnQykOcBq9r9zOVTfUmCsZfzCb2G63r0f_DkPRv6Ll9eaRKn1TeRc5Q&oh=00_AQMdvwRmPptAYXpL-ulnmS89xl0zOifJehi8Zgx3daUulw&oe=6AC087BC'],
    categoryId: 'cat-1',
    categoryName: 'Festive Ensembles & Kurta Sets',
    status: 'active',
    sku: 'MRID-VELVET-04',
    stock: 18,
    views: 940,
    clicks: 430,
    addToCartCount: 160,
    ordersCount: 52,
    revenue: 5148,
  },
];

export const INITIAL_STOREFRONT_THEME: StorefrontTheme = {
  template: 'creator',
  brandName: 'Mridalini Official',
  handle: 'mridaliniofficial',
  bio: 'Curated contemporary ethnic wear & artisanal festive ensembles. Automated Instagram comment-to-DM checkout.',
  tagline: 'Timeless Elegance, Modern Grace.',
  avatarUrl: 'https://scontent-tpe1-1.cdninstagram.com/v/t51.82787-19/751206463_18202213531329609_2979703026788183658_n.jpg?stp=dst-jpg_s206x206_tt6&_nc_cat=106&ccb=7-5&_nc_sid=bf7eb4&efg=eyJ2ZW5jb2RlX3RhZyI6InByb2ZpbGVfcGljLnd3dy43MzUuQzMifQ%3D%3D&_nc_ohc=1iTBTT2cCVMQ7kNvwHhVxPx&_nc_oc=AdpbeMGUNaoWMf1vtJkvK0nrDV869KqyfUJEFUtHS-hziAQec54XJ78wL0uI_eyP9xodbvfMDhDPfIhIyJ2Jc--h&_nc_zt=24&_nc_ht=scontent-tpe1-1.cdninstagram.com&edm=AP4hL3IEAAAA&_nc_gid=-ofZrpsEuBGWhfNnZOFxjA&_nc_tpa=Q5bMBQIcDoLaz2pPFwul3NxYYkPMXgmpsgRNzIZyFBgd8vYS7HE_HPjBipkl_zMtaqUnYYr7sWhUWPvgGA&oh=00_AQNKN382gsABtREPVFPXJRoQRQ-nzkIAgxz6wa_MPs9Crw&oe=6AC0A40B',
  coverUrl: 'https://scontent-tpe1-1.cdninstagram.com/v/t51.82787-15/759408922_18203433670329609_4651465586871677850_n.webp?stp=dst-jpg_e35_tt6&_nc_cat=105&ig_cache_key=Mzk1MDcyNDU4MjEzMDQ3MTc1Mw%3D%3D.3-ccb7-5&ccb=7-5&_nc_sid=a54f6b&efg=eyJlZmdfdGFnIjoiYmVzdF9pbWFnZV91cmxnZW4uRkVFRC5DMyJ9&_nc_ohc=8mFyUENJVCIQ7kNvwE2AhgJ&_nc_oc=AdqW_pUytybg9Kdo_sowbA97rdt6Uyn2a23woREP0K-sBhhV7XC3cSKE87waGrLdV3_vlfaigdjus9r1CQfjtul5&_nc_zt=23&_nc_ht=scontent-tpe1-1.cdninstagram.com&edm=ANo9K5cEAAAA&_nc_gid=QtKzGqASPYGF0NL_5VfPVA&_nc_tpa=Q5bMBQK_gVaz89JQXX5TPHjjcC5CtJIOIWI5v0q1mk8EvzELJTIGJvLvKTPUkGGeGAhCVX291OOaXdoWdA&oh=00_AQMfDU3Gh7HFfLZsBYxxfOeqis05_FN3boTb2jfsp2pC7Q&oe=6AC09EEF',
  primaryColor: '#BE185D',
  secondaryColor: '#9D174D',
  font: 'Plus Jakarta Sans',
  mode: 'light',
  buttonStyle: 'rounded-xl',
  productLayout: 'grid',
  featuredProductIds: ['prod-1', 'prod-2', 'prod-3', 'prod-4'],
  socialLinks: {
    instagram: 'https://instagram.com/mridaliniofficial',
    whatsapp: 'https://wa.me/919876543210',
    website: 'https://mridalini.com',
  },
};

export const INITIAL_CUSTOM_DOMAIN: CustomDomainConfig = {
  domain: 'shop.mridalini.com',
  status: 'connected',
  sslStatus: 'active',
  type: 'CNAME',
  name: 'shop',
  targetValue: 'domains.autodm.com',
  configuredAt: 'Sep 28, 2026',
};

// ==========================================
// MULTI-CHANNEL AUTOMATIONS (Visual Node Architecture)
// ==========================================

export const INITIAL_AUTOMATIONS: Automation[] = [
  {
    id: 'auto-ig-1',
    name: 'Instagram Reel Comment Auto-DM (BUY & PRICE)',
    channel: 'instagram',
    triggerType: 'instagram_comment',
    conditionType: 'keyword_contains',
    actionType: 'send_message',
    steps: [
      { id: 's1', type: 'trigger', title: 'Instagram Reel Comment', channel: 'instagram', config: { postCode: 'DbTt-X3yduU' } },
      { id: 's2', type: 'condition', title: 'Keyword contains: BUY, PRICE, or ORDER', config: { keywords: ['buy', 'price', 'order', 'shop'] } },
      { id: 's3', type: 'action', title: 'Send Automated Direct Message', channel: 'instagram', config: { template: 'Hey {{name}}! Here is your exclusive store link.' } },
      { id: 's4', type: 'action', title: 'Attach Product Card & Code MRIDALINI10', config: { productId: 'prod-1' } },
    ],
    postId: '17896959432557975',
    postCode: 'DbTt-X3yduU',
    postThumbnail: 'https://scontent-tpe1-1.cdninstagram.com/v/t51.71878-15/758400594_1074641168558022_1484593028835977962_n.jpg?stp=dst-jpg_e35_tt6&_nc_cat=106&ccb=7-5&_nc_sid=a54f6b&efg=eyJlZmdfdGFnIjoiYmVzdF9pbWFnZV91cmxnZW4uQ0xJUFMuQzMifQ%3D%3D&_nc_ohc=HVabN2FWD9oQ7kNvwFM9FBh&_nc_oc=AdoP2Bf2hCiK3OAEETclYPi9L9VgUDxABn71tcLNI0MORMe1y1HOucbGZiNFCAABwHgqnL4umtwQvnzhrNFuOo1c&_nc_zt=23&_nc_ht=scontent-tpe1-1.cdninstagram.com&edm=ANo9K5cEAAAA&_nc_gid=QtKzGqASPYGF0NL_5VfPVA&_nc_tpa=Q5bMBQLk8FizTLNX151tK6mV209F174oTBZUa2rPNQc4Hn82y_MIhwf4FvvS5LLXgF8eSfd7z28Gxuvjrg&oh=00_AQOm2l9bXA6nStQi0kisLsse273EDDqCS5zrbE2spawy_A&oe=6AC085D9',
    postCaption: 'New festive collection launch! Comment BUY or PRICE to receive your private shopping link in DMs ✨',
    keyword: 'buy',
    keywords: ['buy', 'price', 'order', 'shop', 'link'],
    replyMessage: "Hey @{{username}}! ✨ Thank you for loving our new collection. Here is your direct link to shop this look:\n{{product_link}}\n\nUse code MRIDALINI10 for 10% off at checkout today!",
    dmMessage: "Hey @{{username}}! ✨ Thank you for loving our new collection. Here is your direct link to shop this look:\n{{product_link}}\n\nUse code MRIDALINI10 for 10% off at checkout today!",
    targetProductId: 'prod-1',
    status: 'active',
    createdAt: 'Sep 28, 2026',
    triggerCount: 842,
    dmsSent: 820,
    clicks: 694,
    conversions: 142,
    conversionRevenue: 11218,
  },
  {
    id: 'auto-ig-2',
    name: 'Instagram Post Catalog Auto-DM (LINK)',
    channel: 'instagram',
    triggerType: 'instagram_comment',
    conditionType: 'keyword_contains',
    actionType: 'send_message',
    steps: [
      { id: 's1', type: 'trigger', title: 'Instagram Post Comment', channel: 'instagram', config: { postCode: 'DbTyxNbSlNJ' } },
      { id: 's2', type: 'condition', title: 'Keyword contains: LINK or CATALOG', config: { keywords: ['link', 'catalog', 'details'] } },
      { id: 's3', type: 'action', title: 'Send Automated Direct Message', channel: 'instagram', config: { template: 'Hello {{name}}! Here is our full catalog link.' } },
    ],
    postId: '17997579704996102',
    postCode: 'DbTyxNbSlNJ',
    postThumbnail: 'https://scontent-tpe1-1.cdninstagram.com/v/t51.82787-15/759408922_18203433670329609_4651465586871677850_n.webp?stp=dst-jpg_e35_tt6&_nc_cat=105&ig_cache_key=Mzk1MDcyNDU4MjEzMDQ3MTc1Mw%3D%3D.3-ccb7-5&ccb=7-5&_nc_sid=a54f6b&efg=eyJlZmdfdGFnIjoiYmVzdF9pbWFnZV91cmxnZW4uRkVFRC5DMyJ9&_nc_ohc=8mFyUENJVCIQ7kNvwE2AhgJ&_nc_oc=AdqW_pUytybg9Kdo_sowbA97rdt6Uyn2a23woREP0K-sBhhV7XC3cSKE87waGrLdV3_vlfaigdjus9r1CQfjtul5&_nc_zt=23&_nc_ht=scontent-tpe1-1.cdninstagram.com&edm=ANo9K5cEAAAA&_nc_gid=QtKzGqASPYGF0NL_5VfPVA&_nc_tpa=Q5bMBQK_gVaz89JQXX5TPHjjcC5CtJIOIWI5v0q1mk8EvzELJTIGJvLvKTPUkGGeGAhCVX291OOaXdoWdA&oh=00_AQMfDU3Gh7HFfLZsBYxxfOeqis05_FN3boTb2jfsp2pC7Q&oe=6AC09EEF',
    postCaption: 'Handcrafted pure silk anarkali. Comment LINK for sizing & order details!',
    keyword: 'link',
    keywords: ['link', 'catalog', 'details', 'collection'],
    replyMessage: "Hello! 💕 Here is the direct link to our festive catalog:\n{{product_link}}\nEnjoy zero-commission checkout and free express courier!",
    dmMessage: "Hello! 💕 Here is the direct link to our festive catalog:\n{{product_link}}\nEnjoy zero-commission checkout and free express courier!",
    targetProductId: 'prod-2',
    status: 'active',
    createdAt: 'Sep 28, 2026',
    triggerCount: 395,
    dmsSent: 388,
    clicks: 310,
    conversions: 64,
    conversionRevenue: 8256,
  },
  {
    id: 'auto-wa-1',
    name: 'WhatsApp Concierge Instant Order Flow',
    channel: 'whatsapp',
    triggerType: 'whatsapp_incoming_message',
    conditionType: 'keyword_contains',
    actionType: 'send_product',
    steps: [
      { id: 's1', type: 'trigger', title: 'Inbound WhatsApp Message', channel: 'whatsapp', config: { target: 'all_contacts' } },
      { id: 's2', type: 'condition', title: 'Message contains: PRICE or BUY', config: { keywords: ['price', 'buy', 'catalog'] } },
      { id: 's3', type: 'action', title: 'Send Official WhatsApp Template', channel: 'whatsapp', config: { template: 'product_showcase_v1' } },
    ],
    keyword: 'price',
    keywords: ['price', 'buy', 'cost', 'quote'],
    replyMessage: "Hello! 👋 Welcome to Mridalini Official concierge. Our handcrafted festive collection starts at $39 with free courier delivery.\n\nBrowse & order securely below:\n{{product_link}}",
    dmMessage: "Hello! 👋 Welcome to Mridalini Official concierge. Our handcrafted festive collection starts at $39 with free courier delivery.\n\nBrowse & order securely below:\n{{product_link}}",
    targetProductId: 'prod-1',
    postCode: 'WA-MSG',
    postThumbnail: 'https://scontent-tpe1-1.cdninstagram.com/v/t51.71878-15/758400594_1074641168558022_1484593028835977962_n.jpg?stp=dst-jpg_e35_tt6&_nc_cat=106&ccb=7-5&_nc_sid=a54f6b&efg=eyJlZmdfdGFnIjoiYmVzdF9pbWFnZV91cmxnZW4uQ0xJUFMuQzMifQ%3D%3D&_nc_ohc=HVabN2FWD9oQ7kNvwFM9FBh&_nc_oc=AdoP2Bf2hCiK3OAEETclYPi9L9VgUDxABn71tcLNI0MORMe1y1HOucbGZiNFCAABwHgqnL4umtwQvnzhrNFuOo1c&_nc_zt=23&_nc_ht=scontent-tpe1-1.cdninstagram.com&edm=ANo9K5cEAAAA&_nc_gid=QtKzGqASPYGF0NL_5VfPVA&_nc_tpa=Q5bMBQLk8FizTLNX151tK6mV209F174oTBZUa2rPNQc4Hn82y_MIhwf4FvvS5LLXgF8eSfd7z28Gxuvjrg&oh=00_AQOm2l9bXA6nStQi0kisLsse273EDDqCS5zrbE2spawy_A&oe=6AC085D9',
    status: 'active',
    createdAt: 'Sep 28, 2026',
    triggerCount: 418,
    dmsSent: 405,
    clicks: 312,
    conversions: 62,
    conversionRevenue: 5518,
  },
];

// ==========================================
// UNIFIED CUSTOMER CRM (Cross-Channel Identities)
// ==========================================

export const INITIAL_CUSTOMERS: Customer[] = [
  {
    id: 'cust-1',
    name: 'Priya Sharma',
    email: 'priya.sharma@gmail.com',
    phone: '+91 98765 43210',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=500&auto=format&fit=crop&q=80',
    source: 'Instagram',
    primaryChannel: 'instagram',
    instagramUsername: 'priya_style',
    identities: [
      { id: 'id-1', channel: 'instagram', handle: '@priya_style', isPrimary: true, verifiedAt: 'Sep 28, 2026' },
      { id: 'id-2', channel: 'whatsapp', handle: '+91 98765 43210', isPrimary: false, verifiedAt: 'Sep 28, 2026' },
    ],
    interestedProducts: ['Mridalini Signature Embroidered Kurta Set'],
    ordersCount: 2,
    totalSpent: 158,
    status: 'repeat',
    lastInteraction: '10 mins ago',
    createdAt: 'Sep 28, 2026',
    tags: ['Festive Buyer', 'Instagram Lead', 'VIP'],
    notes: 'Commented BUY on Instagram Reel DbTt-X3yduU. Received instant automated DM and completed checkout within 2 minutes.',
  },
  {
    id: 'cust-2',
    name: 'Theo Evans',
    email: 'theo@devlabs.io',
    phone: '+91 98112 23344',
    avatarUrl: '/src/assets/images/avatar_ankit_1790498690280.jpg',
    source: 'TikTok',
    primaryChannel: 'tiktok',
    instagramUsername: 'theo.codes',
    identities: [
      { id: 'id-4', channel: 'tiktok', handle: '@theo.codes', isPrimary: true, verifiedAt: 'Apr 23, 2026' },
      { id: 'id-5', channel: 'whatsapp', handle: '+91 98112 23344', isPrimary: false, verifiedAt: 'Apr 24, 2026' },
    ],
    interestedProducts: ['Acoustic Studio Pro Wireless Headphones'],
    ordersCount: 1,
    totalSpent: 89,
    status: 'purchased',
    lastInteraction: '2 hours ago',
    createdAt: 'Apr 23, 2026',
    tags: ['Hardware Buyer', 'TikTok Lead'],
    notes: 'Discovered product via TikTok video. Confirmed courier tracking via WhatsApp concierge.',
  },
  {
    id: 'cust-3',
    name: 'Maya Kapoor',
    email: 'mayak@fashionstudio.com',
    phone: '+91 97234 56789',
    avatarUrl: '/src/assets/images/avatar_sarah_1790499318738.jpg',
    source: 'Instagram',
    primaryChannel: 'instagram',
    instagramUsername: 'maya.k',
    identities: [
      { id: 'id-6', channel: 'instagram', handle: '@maya.k', isPrimary: true, verifiedAt: 'Apr 25, 2026' },
      { id: 'id-7', channel: 'telegram', handle: '@mayakapoor', isPrimary: false, verifiedAt: 'Apr 26, 2026' },
    ],
    interestedProducts: ['1-on-1 Multi-Channel Funnel Audit & Setup'],
    ordersCount: 1,
    totalSpent: 99,
    status: 'purchased',
    lastInteraction: 'Yesterday',
    createdAt: 'Apr 25, 2026',
    tags: ['Coaching Client', 'High Ticket'],
    notes: 'Booked consulting slot. Telegram bot sent her calendar invitation and prep Notion board.',
  },
  {
    id: 'cust-4',
    name: 'Alex Rivera',
    email: 'alex@creatorcollective.net',
    phone: '+91 96543 21098',
    avatarUrl: '/src/assets/images/avatar_ankit_1790498690280.jpg',
    source: 'WhatsApp',
    primaryChannel: 'whatsapp',
    instagramUsername: 'alex_creates',
    identities: [
      { id: 'id-8', channel: 'whatsapp', handle: '+91 96543 21098', isPrimary: true, verifiedAt: 'Apr 27, 2026' },
      { id: 'id-9', channel: 'tiktok', handle: '@alex_creates', isPrimary: false, verifiedAt: 'Apr 27, 2026' },
    ],
    interestedProducts: ['Creator Accelerator 2026'],
    ordersCount: 0,
    totalSpent: 0,
    status: 'checkout',
    lastInteraction: '35 mins ago',
    createdAt: 'Apr 27, 2026',
    tags: ['Abandoned Checkout', 'High Value Lead'],
    notes: 'Initiated checkout on Razorpay via WhatsApp link. AutoDM follow-up sequence active.',
  },
  {
    id: 'cust-5',
    name: 'Vikram Malhotra',
    email: 'vikram@fintechpulse.in',
    phone: '+91 99887 76655',
    avatarUrl: '/src/assets/images/avatar_ankit_1790498690280.jpg',
    source: 'Telegram',
    primaryChannel: 'telegram',
    instagramUsername: 'vikram_m',
    identities: [
      { id: 'id-10', channel: 'telegram', handle: '@vikram_m', isPrimary: true, verifiedAt: 'Apr 26, 2026' },
      { id: 'id-11', channel: 'whatsapp', handle: '+91 99887 76655', isPrimary: false, verifiedAt: 'Apr 26, 2026' },
    ],
    interestedProducts: ['42-Page Social Commerce Playbook'],
    ordersCount: 1,
    totalSpent: 19,
    status: 'purchased',
    lastInteraction: '4 hours ago',
    createdAt: 'Apr 26, 2026',
    tags: ['Telegram VIP', 'Digital Buyer'],
    notes: 'Triggered /buy command in Telegram bot. Purchased PDF playbook within 90 seconds.',
  },
];

// ==========================================
// UNIFIED INBOX CONVERSATIONS (All Channels in One Place)
// ==========================================

export const INITIAL_CONVERSATIONS: Conversation[] = [
  {
    id: 'conv-ig-1',
    customerId: 'cust-1',
    customerName: 'Priya Sharma',
    channel: 'instagram',
    channelHandle: '@priya_style',
    instagramUsername: 'priya_style',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=500&auto=format&fit=crop&q=80',
    lastMessage: 'Thank you! Just placed my order for the Emerald Green set.',
    lastMessageTime: '10m ago',
    unreadCount: 0,
    status: 'open',
    assignedStatus: 'assigned',
    tags: ['Order Placed', 'VIP', 'Instagram'],
    messages: [
      { id: 'm-1', sender: 'customer', text: 'Where can I buy the outfit in your latest reel? Commented BUY!', timestamp: '2:40 PM', channel: 'instagram' },
      {
        id: 'm-2',
        sender: 'system_bot',
        text: "Hey @priya_style! ✨ Here is the direct link to the Mridalini Signature Embroidered Kurta Set:\nhttps://shop.mridalini.com/p/mridalini-signature-kurta-set\n\nUse code MRIDALINI10 for 10% off today!",
        timestamp: '2:40 PM',
        channel: 'instagram',
        productCard: {
          title: 'Mridalini Signature Embroidered Kurta Set',
          price: 79,
          image: 'https://scontent-tpe1-1.cdninstagram.com/v/t51.71878-15/758400594_1074641168558022_1484593028835977962_n.jpg?stp=dst-jpg_e35_tt6&_nc_cat=106&ccb=7-5&_nc_sid=a54f6b&efg=eyJlZmdfdGFnIjoiYmVzdF9pbWFnZV91cmxnZW4uQ0xJUFMuQzMifQ%3D%3D&_nc_ohc=HVabN2FWD9oQ7kNvwFM9FBh&_nc_oc=AdoP2Bf2hCiK3OAEETclYPi9L9VgUDxABn71tcLNI0MORMe1y1HOucbGZiNFCAABwHgqnL4umtwQvnzhrNFuOo1c&_nc_zt=23&_nc_ht=scontent-tpe1-1.cdninstagram.com&edm=ANo9K5cEAAAA&_nc_gid=QtKzGqASPYGF0NL_5VfPVA&_nc_tpa=Q5bMBQLk8FizTLNX151tK6mV209F174oTBZUa2rPNQc4Hn82y_MIhwf4FvvS5LLXgF8eSfd7z28Gxuvjrg&oh=00_AQOm2l9bXA6nStQi0kisLsse273EDDqCS5zrbE2spawy_A&oe=6AC085D9',
          link: 'https://shop.mridalini.com/p/mridalini-signature-kurta-set',
        },
      },
      { id: 'm-3', sender: 'customer', text: 'Does it come with matching pants and dupatta?', timestamp: '2:42 PM', channel: 'instagram' },
      { id: 'm-4', sender: 'creator', text: 'Yes Priya! It is a complete 3-piece ensemble with pure chanderi silk pants and hand-embroidered organza dupatta.', timestamp: '2:44 PM', channel: 'instagram' },
      { id: 'm-5', sender: 'customer', text: 'Thank you! Just placed my order for the Emerald Green set.', timestamp: '2:46 PM', channel: 'instagram' },
    ],
  },
  {
    id: 'conv-wa-1',
    customerId: 'cust-2',
    customerName: 'Aarti Mehra',
    channel: 'whatsapp',
    channelHandle: '+91 98112 23344',
    instagramUsername: 'aarti_m',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=500&auto=format&fit=crop&q=80',
    lastMessage: 'Great, thanks for the dispatch confirmation!',
    lastMessageTime: '1h ago',
    unreadCount: 0,
    status: 'open',
    assignedStatus: 'bot_handling',
    tags: ['WhatsApp', 'Silk Anarkali', 'Dispatched'],
    messages: [
      { id: 'mw-1', sender: 'customer', text: 'Hi! Inquired on Instagram about the Pure Silk Anarkali Gown. Can I order via WhatsApp?', timestamp: '11:15 AM', channel: 'whatsapp' },
      {
        id: 'mw-2',
        sender: 'system_bot',
        text: "Hi Aarti! ✨ Yes, you can complete your order directly with instant UPI or Cards:\nhttps://shop.mridalini.com/p/pure-silk-anarkali-gown",
        timestamp: '11:15 AM',
        channel: 'whatsapp',
        productCard: {
          title: 'Handcrafted Pure Silk Anarkali Gown',
          price: 129,
          image: 'https://scontent-tpe1-1.cdninstagram.com/v/t51.82787-15/759408922_18203433670329609_4651465586871677850_n.webp?stp=dst-jpg_e35_tt6&_nc_cat=105&ig_cache_key=Mzk1MDcyNDU4MjEzMDQ3MTc1Mw%3D%3D.3-ccb7-5&ccb=7-5&_nc_sid=a54f6b&efg=eyJlZmdfdGFnIjoiYmVzdF9pbWFnZV91cmxnZW4uRkVFRC5DMyJ9&_nc_ohc=8mFyUENJVCIQ7kNvwE2AhgJ&_nc_oc=AdqW_pUytybg9Kdo_sowbA97rdt6Uyn2a23woREP0K-sBhhV7XC3cSKE87waGrLdV3_vlfaigdjus9r1CQfjtul5&_nc_zt=23&_nc_ht=scontent-tpe1-1.cdninstagram.com&edm=ANo9K5cEAAAA&_nc_gid=QtKzGqASPYGF0NL_5VfPVA&_nc_tpa=Q5bMBQK_gVaz89JQXX5TPHjjcC5CtJIOIWI5v0q1mk8EvzELJTIGJvLvKTPUkGGeGAhCVX291OOaXdoWdA&oh=00_AQMfDU3Gh7HFfLZsBYxxfOeqis05_FN3boTb2jfsp2pC7Q&oe=6AC09EEF',
          link: 'https://shop.mridalini.com/p/pure-silk-anarkali-gown',
        },
      },
      { id: 'mw-3', sender: 'customer', text: 'Order placed! Here is the order confirmation #ORD-8491.', timestamp: '11:22 AM', channel: 'whatsapp' },
      { id: 'mw-4', sender: 'creator', text: 'Order received Aarti! Dispatching via BlueDart Express this afternoon. Tracking: BLU9481920.', timestamp: '11:30 AM', channel: 'whatsapp' },
      { id: 'mw-5', sender: 'customer', text: 'Great, thanks for the dispatch confirmation!', timestamp: '11:32 AM', channel: 'whatsapp' },
    ],
  },
  {
    id: 'conv-tg-1',
    customerId: 'cust-5',
    customerName: 'Vikram Malhotra',
    channel: 'telegram',
    channelHandle: '@vikram_m',
    instagramUsername: 'vikram_m',
    avatarUrl: '/src/assets/images/avatar_ankit_1790498690280.jpg',
    lastMessage: 'Awesome bot! The PDF playbook downloaded automatically.',
    lastMessageTime: '3h ago',
    unreadCount: 0,
    status: 'closed',
    assignedStatus: 'bot_handling',
    tags: ['Telegram Bot', 'Digital Asset'],
    messages: [
      { id: 'mt-1', sender: 'customer', text: '/buy', timestamp: '9:00 AM', channel: 'telegram' },
      {
        id: 'mt-2',
        sender: 'system_bot',
        text: "Welcome to AutoDM Store Bot! Here is our 42-page Social Commerce Playbook:\nhttps://shop.ankitsharma.me/p/social-commerce-playbook",
        timestamp: '9:00 AM',
        channel: 'telegram',
        productCard: {
          title: '42-Page Multi-Channel Social Commerce Playbook',
          price: 19,
          image: '/src/assets/images/digital_product_1790499336046.jpg',
          link: 'https://shop.ankitsharma.me/p/social-commerce-playbook',
        },
      },
      { id: 'mt-3', sender: 'customer', text: 'Awesome bot! The PDF playbook downloaded automatically.', timestamp: '9:05 AM', channel: 'telegram' },
    ],
  },
  {
    id: 'conv-tt-1',
    customerId: 'cust-4',
    customerName: 'Alex Rivera',
    channel: 'tiktok',
    channelHandle: '@alex_creates',
    instagramUsername: 'alex_creates',
    avatarUrl: '/src/assets/images/avatar_ankit_1790498690280.jpg',
    lastMessage: 'Will check out the discount code today.',
    lastMessageTime: '45m ago',
    unreadCount: 1,
    status: 'open',
    assignedStatus: 'escalated',
    tags: ['TikTok', 'Lead', 'Follow-up'],
    messages: [
      { id: 'mtt-1', sender: 'customer', text: 'Hey Ankit, left a comment on your viral TikTok about creator funnels.', timestamp: '1:45 PM', channel: 'tiktok' },
      {
        id: 'mtt-2',
        sender: 'system_bot',
        text: "Hey Alex! Thanks for reaching out. Here is our direct storefront link:\nhttps://shop.ankitsharma.me",
        timestamp: '1:45 PM',
        channel: 'tiktok',
      },
      { id: 'mtt-3', sender: 'customer', text: 'Will check out the discount code today.', timestamp: '1:50 PM', channel: 'tiktok' },
    ],
  },
];

// ==========================================
// STOREFRONT ORDERS (With Channel Attribution)
// ==========================================

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'ord-8492',
    orderNumber: '#ORD-8492',
    customerId: 'cust-1',
    customerName: 'Sarah Jenkins',
    customerEmail: 'sarah.j@gmail.com',
    channel: 'instagram',
    channelHandle: '@sarah_123',
    instagramUsername: 'sarah_123',
    items: [
      {
        productId: 'prod-1',
        title: 'Mridalini Signature Embroidered Kurta Set',
        type: 'physical',
        price: 79,
        quantity: 1,
        variantName: 'Emerald Green (S/M)',
        image: 'https://scontent-tpe1-1.cdninstagram.com/v/t51.71878-15/758400594_1074641168558022_1484593028835977962_n.jpg?stp=dst-jpg_e35_tt6&_nc_cat=106&ccb=7-5&_nc_sid=a54f6b&efg=eyJlZmdfdGFnIjoiYmVzdF9pbWFnZV91cmxnZW4uQ0xJUFMuQzMifQ%3D%3D&_nc_ohc=HVabN2FWD9oQ7kNvwFM9FBh&_nc_oc=AdoP2Bf2hCiK3OAEETclYPi9L9VgUDxABn71tcLNI0MORMe1y1HOucbGZiNFCAABwHgqnL4umtwQvnzhrNFuOo1c&_nc_zt=23&_nc_ht=scontent-tpe1-1.cdninstagram.com&edm=ANo9K5cEAAAA&_nc_gid=QtKzGqASPYGF0NL_5VfPVA&_nc_tpa=Q5bMBQLk8FizTLNX151tK6mV209F174oTBZUa2rPNQc4Hn82y_MIhwf4FvvS5LLXgF8eSfd7z28Gxuvjrg&oh=00_AQOm2l9bXA6nStQi0kisLsse273EDDqCS5zrbE2spawy_A&oe=6AC085D9',
      },
    ],
    subtotal: 79,
    shipping: 0,
    total: 79,
    paymentGateway: 'Razorpay',
    paymentId: 'pay_Lp83Kn92a',
    paymentStatus: 'paid',
    orderStatus: 'delivered',
    createdAt: 'Today, 2:46 PM',
  },
  {
    id: 'ord-8491',
    orderNumber: '#ORD-8491',
    customerId: 'cust-2',
    customerName: 'Aarti Mehra',
    customerEmail: 'aarti.mehra@gmail.com',
    channel: 'whatsapp',
    channelHandle: '+91 98112 23344',
    instagramUsername: 'aarti_m',
    items: [
      {
        productId: 'prod-2',
        title: 'Handcrafted Pure Silk Anarkali Gown',
        type: 'physical',
        price: 129,
        quantity: 1,
        variantName: 'Opal Ivory',
        image: 'https://scontent-tpe1-1.cdninstagram.com/v/t51.82787-15/759408922_18203433670329609_4651465586871677850_n.webp?stp=dst-jpg_e35_tt6&_nc_cat=105&ig_cache_key=Mzk1MDcyNDU4MjEzMDQ3MTc1Mw%3D%3D.3-ccb7-5&ccb=7-5&_nc_sid=a54f6b&efg=eyJlZmdfdGFnIjoiYmVzdF9pbWFnZV91cmxnZW4uRkVFRC5DMyJ9&_nc_ohc=8mFyUENJVCIQ7kNvwE2AhgJ&_nc_oc=AdqW_pUytybg9Kdo_sowbA97rdt6Uyn2a23woREP0K-sBhhV7XC3cSKE87waGrLdV3_vlfaigdjus9r1CQfjtul5&_nc_zt=23&_nc_ht=scontent-tpe1-1.cdninstagram.com&edm=ANo9K5cEAAAA&_nc_gid=QtKzGqASPYGF0NL_5VfPVA&_nc_tpa=Q5bMBQK_gVaz89JQXX5TPHjjcC5CtJIOIWI5v0q1mk8EvzELJTIGJvLvKTPUkGGeGAhCVX291OOaXdoWdA&oh=00_AQMfDU3Gh7HFfLZsBYxxfOeqis05_FN3boTb2jfsp2pC7Q&oe=6AC09EEF',
      },
    ],
    subtotal: 129,
    shipping: 0,
    total: 129,
    paymentGateway: 'Cashfree',
    paymentId: 'cf_ord_938104',
    paymentStatus: 'paid',
    orderStatus: 'shipped',
    createdAt: 'Today, 11:22 AM',
    shippingAddress: {
      address: 'Flat 402, Green Glen Layout, Bellandur',
      city: 'Bengaluru',
      state: 'Karnataka',
      postalCode: '560103',
    },
  },
  {
    id: 'ord-8490',
    orderNumber: '#ORD-8490',
    customerId: 'cust-3',
    customerName: 'Maya Kapoor',
    customerEmail: 'mayak@fashionstudio.com',
    channel: 'instagram',
    channelHandle: '@maya.k',
    instagramUsername: 'maya.k',
    items: [
      {
        productId: 'prod-3',
        title: 'Artisanal Zari Bordered Tissue Stole',
        type: 'physical',
        price: 39,
        quantity: 1,
        image: 'https://scontent-tpe1-1.cdninstagram.com/v/t51.82787-15/757954711_18203430457329609_9017753783645031254_n.webp?stp=dst-jpg_e35_tt6&_nc_cat=107&ig_cache_key=Mzk1MDcxODAyOTMwMjEwNjc0OQ%3D%3D.3-ccb7-5&ccb=7-5&_nc_sid=a54f6b&efg=eyJlZmdfdGFnIjoiYmVzdF9pbWFnZV91cmxnZW4uRkVFRC5DMyJ9&_nc_ohc=PZ6JxjyCOIMQ7kNvwHbKImY&_nc_oc=AdpSGnm8N4gVVfSvCXbvfKwmwbxhOjGOc2qgOAgYnn_owlaExFMNwlXy5en-mbZi48_4ZqJBbJmwkjmFHsDDYivD&_nc_zt=23&_nc_ht=scontent-tpe1-1.cdninstagram.com&edm=ANo9K5cEAAAA&_nc_gid=QtKzGqASPYGF0NL_5VfPVA&_nc_tpa=Q5bMBQLVIucMKNhf8xc_F5Fu2KB2nB03DdoJK_3-twvUMmmQ7zUH7TSdusD1BfBP4a-etgVkOo1sqLqJYw&oh=00_AQOzXGrS1hjbNVT5gMe3FChLf42tCl9_7-cb6vY-qFRapg&oe=6AC07DC2',
      },
    ],
    subtotal: 39,
    shipping: 0,
    total: 39,
    paymentGateway: 'Razorpay',
    paymentId: 'pay_Kq92Lp01a',
    paymentStatus: 'paid',
    orderStatus: 'processing',
    createdAt: 'Yesterday, 4:15 PM',
  },
  {
    id: 'ord-8489',
    orderNumber: '#ORD-8489',
    customerId: 'cust-5',
    customerName: 'Vikram Malhotra',
    customerEmail: 'vikram@fintechpulse.in',
    channel: 'telegram',
    channelHandle: '@vikram_m',
    instagramUsername: 'vikram_m',
    items: [
      {
        productId: 'prod-3',
        title: '42-Page Multi-Channel Social Commerce Playbook',
        type: 'digital',
        price: 19,
        quantity: 1,
        image: '/src/assets/images/digital_product_1790499336046.jpg',
      },
    ],
    subtotal: 19,
    shipping: 0,
    total: 19,
    paymentGateway: 'Razorpay',
    paymentId: 'pay_Jp71Mn03b',
    paymentStatus: 'paid',
    orderStatus: 'delivered',
    createdAt: '2 days ago',
  },
];

// ==========================================
// CHANNEL ATTRIBUTION & REVENUE ANALYTICS
// ==========================================

export const CHANNEL_ANALYTICS: ChannelAnalyticsData[] = [
  {
    channel: 'instagram',
    name: 'Instagram',
    color: '#E1306C',
    iconBg: 'from-amber-400 via-pink-500 to-purple-600',
    messages: 1842,
    engagement: 4210,
    leads: 680,
    productClicks: 1420,
    storeVisits: 3840,
    orders: 218,
    revenue: 25000,
  },
  {
    channel: 'tiktok',
    name: 'TikTok',
    color: '#00F2FE',
    iconBg: 'from-cyan-400 via-black to-pink-500',
    messages: 950,
    engagement: 3100,
    leads: 420,
    productClicks: 980,
    storeVisits: 2450,
    orders: 142,
    revenue: 12000,
  },
  {
    channel: 'whatsapp',
    name: 'WhatsApp',
    color: '#25D366',
    iconBg: 'from-emerald-500 to-green-600',
    messages: 620,
    engagement: 1420,
    leads: 310,
    productClicks: 590,
    storeVisits: 1240,
    orders: 94,
    revenue: 8000,
  },
  {
    channel: 'telegram',
    name: 'Telegram',
    color: '#229ED9',
    iconBg: 'from-sky-400 to-blue-600',
    messages: 480,
    engagement: 980,
    leads: 210,
    productClicks: 420,
    storeVisits: 840,
    orders: 51,
    revenue: 5000,
  },
];

export const INITIAL_PAYMENT_CONFIGS: PaymentGatewayConfig[] = [
  {
    provider: 'Razorpay',
    isConnected: true,
    merchantId: 'rzp_live_merch_849201',
    keyId: 'rzp_live_9482710398',
    webhookSecretSet: true,
    webhookUrl: 'https://api.autodm.com/webhooks/razorpay/v1',
    currency: 'INR / USD',
    mode: 'live',
    connectedAt: 'Connected on Jan 14, 2026',
  },
  {
    provider: 'Cashfree',
    isConnected: true,
    merchantId: 'cf_app_991823',
    keyId: 'cf_live_key_94810284',
    webhookSecretSet: true,
    webhookUrl: 'https://api.autodm.com/webhooks/cashfree/v1',
    currency: 'INR',
    mode: 'live',
    connectedAt: 'Connected on Feb 02, 2026',
  },
];

export const INITIAL_ACCOUNT = INITIAL_INSTAGRAM_ACCOUNT;

export const INITIAL_ACTIVITIES: ActivityItem[] = [
  {
    id: 'act-1',
    type: 'comment_matched',
    channel: 'instagram',
    title: 'Instagram comment matched',
    subtitle: '“BUY please! Love the green color”',
    context: 'on Reel DbTt-X3yduU',
    timeAgo: '2m ago',
    userHandle: '@priya_style',
  },
  {
    id: 'act-2',
    type: 'dm_sent',
    channel: 'instagram',
    title: 'Automated Direct Message delivered',
    subtitle: '“Hey @priya_style! ✨ Here is your link...”',
    context: 'Reel DbTt-X3yduU',
    timeAgo: '2m ago',
    userHandle: '@priya_style',
  },
  {
    id: 'act-3',
    type: 'comment_matched',
    channel: 'instagram',
    title: 'Instagram comment matched',
    subtitle: '“LINK for sizing details please”',
    context: 'on Post DbTyxNbSlNJ',
    timeAgo: '12m ago',
    userHandle: '@ananya_couture',
  },
  {
    id: 'act-4',
    type: 'dm_sent',
    channel: 'instagram',
    title: 'Automated Direct Message delivered',
    subtitle: '“Hello! 💕 Here is the direct link...”',
    context: 'Post DbTyxNbSlNJ',
    timeAgo: '12m ago',
    userHandle: '@ananya_couture',
  },
  {
    id: 'act-5',
    type: 'order_placed',
    channel: 'instagram',
    title: 'New Order #ORD-8492',
    subtitle: 'Priya Sharma paid $79 via Razorpay',
    context: 'Storefront Direct',
    timeAgo: '24m ago',
    userHandle: '@priya_style',
    amount: 79,
  },
];

export const TOP_KEYWORDS: KeywordMetric[] = [
  { keyword: 'BUY', percentage: 38, count: 682, revenue: 14682, rank: 1, color: '#BE185D' },
  { keyword: 'PRICE', percentage: 26, count: 490, revenue: 9476, rank: 2, color: '#E1306C' },
  { keyword: 'LINK', percentage: 18, count: 320, revenue: 6518, rank: 3, color: '#9D174D' },
  { keyword: 'SHOP', percentage: 10, count: 180, revenue: 3835, rank: 4, color: '#A855F7' },
  { keyword: 'ORDER', percentage: 8, count: 140, revenue: 2762, rank: 5, color: '#25D366' },
];

export const PERFORMANCE_DATA: PerformanceSlice[] = [
  { label: 'Instagram (42%)', percentage: 42, color: '#E1306C', count: 564 },
  { label: 'TikTok (24%)', percentage: 24, color: '#00F2FE', count: 322 },
  { label: 'WhatsApp (20%)', percentage: 20, color: '#25D366', count: 268 },
  { label: 'Telegram (14%)', percentage: 14, color: '#229ED9', count: 188 },
];

export const DMS_OVERVIEW_7D: DailyDMData[] = [
  { date: 'Apr 21', value: 124, dmsSent: 124, comments: 240 },
  { date: 'Apr 22', value: 146, dmsSent: 146, comments: 285 },
  { date: 'Apr 23', value: 168, dmsSent: 168, comments: 310 },
  { date: 'Apr 24', value: 152, dmsSent: 152, comments: 290 },
  { date: 'Apr 25', value: 195, dmsSent: 195, comments: 380 },
  { date: 'Apr 26', value: 215, dmsSent: 215, comments: 412 },
  { date: 'Apr 27', value: 242, dmsSent: 242, comments: 468 },
];

export const DMS_OVERVIEW_30D: DailyDMData[] = [
  { date: 'Apr 01', value: 75, dmsSent: 75 },
  { date: 'Apr 05', value: 110, dmsSent: 110 },
  { date: 'Apr 10', value: 140, dmsSent: 140 },
  { date: 'Apr 15', value: 175, dmsSent: 175 },
  { date: 'Apr 20', value: 195, dmsSent: 195 },
  { date: 'Apr 25', value: 220, dmsSent: 220 },
  { date: 'Apr 27', value: 242, dmsSent: 242 },
];

export const DMS_OVERVIEW_90D: DailyDMData[] = [
  { date: 'Feb', value: 1420, dmsSent: 1420 },
  { date: 'Mar', value: 2890, dmsSent: 2890 },
  { date: 'Apr', value: 4850, dmsSent: 4850 },
];

export const RECENT_LOGS: LogEntry[] = [
  {
    id: 'log-1',
    timestamp: 'Today, 2:48:12 PM',
    level: 'SUCCESS',
    channel: 'instagram',
    event: 'INSTAGRAM_DM_DISPATCHED',
    userHandle: '@sarah_123',
    postCode: '#cKcJ39',
    details: 'Keyword "course" detected in comment. Auto-sent DM with Accelerator checkout link.',
    latencyMs: 142,
  },
  {
    id: 'log-2',
    timestamp: 'Today, 2:40:05 PM',
    level: 'SUCCESS',
    channel: 'whatsapp',
    event: 'WHATSAPP_TEMPLATE_SENT',
    userHandle: '+91 98112 23344',
    postCode: 'WA-MSG',
    details: 'Incoming WhatsApp query "price" verified. Automated product showcase message delivered.',
    latencyMs: 95,
  },
  {
    id: 'log-3',
    timestamp: 'Today, 1:15:42 PM',
    level: 'SUCCESS',
    channel: 'telegram',
    event: 'TELEGRAM_COMMAND_PROCESSED',
    userHandle: '@vikram_m',
    postCode: 'TG-BOT',
    details: 'Command /buy parsed. Instant inline keyboard with digital playbook sent.',
    latencyMs: 64,
  },
  {
    id: 'log-4',
    timestamp: 'Today, 11:22:19 AM',
    level: 'INFO',
    channel: 'tiktok',
    event: 'TIKTOK_COMMENT_FILTERED',
    userHandle: '@alex_creates',
    postCode: '#TT-982',
    details: 'Comment webhook received. Verified capability compliance.',
    latencyMs: 180,
  },
];
