import {
  Product,
  Category,
  StorefrontTheme,
  CustomDomainConfig,
  Automation,
  Customer,
  Conversation,
  Order,
  PaymentGatewayConfig,
  InstagramAccountState,
  SocialChannelAccount,
  ChannelCapability,
  ChannelAnalyticsData,
  PerformanceSlice,
  DailyDMData,
  KeywordMetric,
  LogEntry,
  ActivityItem
} from './types';

// ==========================================
// MULTI-CHANNEL CAPABILITIES & ACCOUNTS
// ==========================================

export const CHANNEL_CAPABILITIES_CONFIG: Record<string, ChannelCapability> = {
  instagram: {
    channel: 'instagram',
    name: 'Instagram',
    comments: true,
    dm: true,
    keywordTrigger: true,
    postBasedAutomation: true,
    templates: false,
    commands: false,
    webhooks: true,
    statusNotice: 'Meta Graph API v19.0 verified. Supports comment webhooks and private direct replies.',
  },
  tiktok: {
    channel: 'tiktok',
    name: 'TikTok',
    comments: 'configurable',
    dm: 'configurable',
    keywordTrigger: 'configurable',
    postBasedAutomation: true,
    templates: false,
    commands: false,
    webhooks: true,
    statusNotice: 'TikTok Open API connected. Direct messaging requires approved partner permissions; comment monitoring active.',
  },
  whatsapp: {
    channel: 'whatsapp',
    name: 'WhatsApp Business',
    comments: false,
    dm: true,
    keywordTrigger: true,
    templates: true,
    commands: false,
    webhooks: true,
    statusNotice: 'Official Meta Cloud API. Supports pre-approved templates, 24h service window, and catalog links.',
  },
  telegram: {
    channel: 'telegram',
    name: 'Telegram',
    comments: false,
    dm: true,
    keywordTrigger: true,
    templates: false,
    commands: true,
    webhooks: true,
    statusNotice: 'Telegram Bot API connected. High rate limits, instant bot commands (/buy, /catalog), and inline buttons.',
  },
};

export const INITIAL_SOCIAL_CHANNELS: SocialChannelAccount[] = [
  {
    id: 'chan-ig-1',
    channel: 'instagram',
    accountName: 'Mridalini Official (Business)',
    handle: '@mridaliniofficial',
    profileImage: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=500&auto=format&fit=crop&q=80',
    isConnected: true,
    status: 'active',
    channelTypeLabel: 'Instagram Business (Graph API v21.0)',
    lastSync: 'Live (Graph API Connected)',
    webhookStatus: 'operational',
    webhookUrl: '/api/webhook/instagram',
    capabilities: CHANNEL_CAPABILITIES_CONFIG.instagram,
    metrics: {
      followers: 12400,
      messagesReceived: 842,
      conversions: 148,
    },
    credentialsHint: 'Connected via Meta App ID: 1097121733196692 (Account ID: 28503726299236968)',
  },
  {
    id: 'chan-tt-1',
    channel: 'tiktok',
    accountName: 'Ankit Tech & Builds',
    handle: '@ankit_tech',
    profileImage: '/src/assets/images/avatar_ankit_1790498690280.jpg',
    isConnected: true,
    status: 'active',
    channelTypeLabel: 'TikTok Creator Account',
    lastSync: '14 mins ago',
    webhookStatus: 'operational',
    webhookUrl: 'https://api.autodm.com/webhooks/v1/tiktok',
    capabilities: CHANNEL_CAPABILITIES_CONFIG.tiktok,
    metrics: {
      followers: 92400,
      messagesReceived: 950,
      conversions: 142,
    },
    credentialsHint: 'TikTok Open API (App ID: 73928192048)',
  },
  {
    id: 'chan-wa-1',
    channel: 'whatsapp',
    accountName: 'AutoDM Store Concierge',
    handle: '+91 98765 43210',
    profileImage: '/src/assets/images/avatar_sarah_1790499318738.jpg',
    isConnected: true,
    status: 'active',
    channelTypeLabel: 'WhatsApp Business Cloud API',
    lastSync: 'Just now',
    webhookStatus: 'operational',
    webhookUrl: 'https://api.autodm.com/webhooks/v1/whatsapp',
    capabilities: CHANNEL_CAPABILITIES_CONFIG.whatsapp,
    metrics: {
      messagesReceived: 620,
      conversions: 94,
    },
    credentialsHint: 'WABA ID: 94810294819 | Meta Verified Phone',
  },
  {
    id: 'chan-tg-1',
    channel: 'telegram',
    accountName: 'AutoDM Store VIP Bot',
    handle: '@AutoDM_AnkitBot',
    profileImage: '/src/assets/images/digital_product_1790499336046.jpg',
    isConnected: true,
    status: 'active',
    channelTypeLabel: 'Telegram Bot API',
    lastSync: '1 min ago',
    webhookStatus: 'operational',
    webhookUrl: 'https://api.autodm.com/webhooks/v1/telegram',
    capabilities: CHANNEL_CAPABILITIES_CONFIG.telegram,
    metrics: {
      subscribers: 14200,
      messagesReceived: 480,
      conversions: 51,
    },
    credentialsHint: 'Bot Token: 719284****:AAH9...',
  },
];

export const INITIAL_INSTAGRAM_ACCOUNT: InstagramAccountState = {
  handle: 'ankit_creates',
  name: 'Ankit Sharma',
  businessName: 'Ankit Sharma Studio',
  category: 'Creator & Tech Educator',
  accountType: 'Creator',
  isConnected: true,
  avatarUrl: '/src/assets/images/avatar_ankit_1790498690280.jpg',
  followers: 48500,
  postsCount: 142,
  apiHealth: '100% Operational',
  webhookActive: true,
  lastSyncedAt: '2 mins ago',
  connectedSince: 'Jan 2026',
  deliveryRate: '99.4%',
};

export const INITIAL_CATEGORIES: Category[] = [
  { id: 'cat-1', name: 'Masterclasses & Courses', slug: 'courses', productCount: 2, order: 1 },
  { id: 'cat-2', name: 'Digital Templates & Guides', slug: 'digital-guides', productCount: 2, order: 2 },
  { id: 'cat-3', name: 'Creator Hardware & Gear', slug: 'gear', productCount: 1, order: 3 },
  { id: 'cat-4', name: '1-on-1 Advisory & Audits', slug: 'consulting', productCount: 1, order: 4 },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-1',
    title: 'Instagram & TikTok Creator Accelerator 2026',
    slug: 'creator-accelerator',
    type: 'digital',
    description: 'The definitive 6-module curriculum to scale from 1,000 to 100,000 engaged followers across Instagram & TikTok, turning organic comment engagement into predictable monthly revenue.',
    price: 49,
    compareAtPrice: 129,
    images: ['/src/assets/images/post_course_launch_1790498703738.jpg'],
    categoryId: 'cat-1',
    categoryName: 'Masterclasses & Courses',
    status: 'active',
    downloadFile: 'accelerator-portal-access-v2.pdf',
    deliverySettings: 'Instant digital access email with private Notion vault & video portal',
    views: 3420,
    clicks: 1840,
    addToCartCount: 620,
    ordersCount: 218,
    revenue: 10682,
  },
  {
    id: 'prod-2',
    title: 'Acoustic Studio Pro Wireless Headphones',
    slug: 'acoustic-studio-pro-headphones',
    type: 'physical',
    description: 'Minimalist studio-grade noise cancelling headphones tuned specifically for video editors, podcasters, and content creators.',
    price: 89,
    compareAtPrice: 149,
    images: ['/src/assets/images/post_product_headphones_1790498714259.jpg'],
    categoryId: 'cat-3',
    categoryName: 'Creator Hardware & Gear',
    status: 'active',
    sku: 'AUDIO-HP-01',
    stock: 42,
    variants: [
      { id: 'var-1', name: 'Matte Obsidian', price: 89, stock: 28 },
      { id: 'var-2', name: 'Lunar Silver', price: 94, stock: 14 },
    ],
    weight: '320g',
    shippingInfo: 'Standard 2-4 day expedited shipping with tracking via Delhivery/Bluedart',
    views: 2140,
    clicks: 980,
    addToCartCount: 310,
    ordersCount: 84,
    revenue: 7476,
  },
  {
    id: 'prod-3',
    title: '42-Page Multi-Channel Social Commerce Playbook',
    slug: 'social-commerce-playbook',
    type: 'digital',
    description: 'Exact scripts, comment trigger blueprints, and DM templates across Instagram, TikTok, WhatsApp, and Telegram that generated over $140,000 in creator storefront sales.',
    price: 19,
    compareAtPrice: 39,
    images: ['/src/assets/images/digital_product_1790499336046.jpg'],
    categoryId: 'cat-2',
    categoryName: 'Digital Templates & Guides',
    status: 'active',
    downloadFile: 'autodm-social-commerce-playbook-2026.pdf',
    deliverySettings: 'Direct secure PDF download link & Notion swipe-file',
    views: 1890,
    clicks: 1120,
    addToCartCount: 480,
    ordersCount: 165,
    revenue: 3135,
  },
  {
    id: 'prod-4',
    title: '1-on-1 Multi-Channel Funnel Audit & Setup',
    slug: 'profile-funnel-audit',
    type: 'service',
    description: '45-minute private consultation with Ankit. We audit your bio, reels, TikTok hooks, WhatsApp concierge routing, and Telegram bot commands to optimize your storefront conversion rate.',
    price: 99,
    compareAtPrice: 199,
    images: ['/src/assets/images/avatar_ankit_1790498690280.jpg'],
    categoryId: 'cat-4',
    categoryName: '1-on-1 Advisory & Audits',
    status: 'active',
    duration: '45 minutes',
    bookingInfo: 'Direct Calendly scheduling link sent via instant confirmation message',
    views: 920,
    clicks: 410,
    addToCartCount: 95,
    ordersCount: 38,
    revenue: 3762,
  },
];

export const INITIAL_STOREFRONT_THEME: StorefrontTheme = {
  template: 'creator',
  brandName: 'Ankit Sharma Studio',
  handle: 'ankit',
  bio: 'Multi-channel social commerce educator helping creators turn comments & chats into direct storefront orders.',
  tagline: 'Automate. Engage. Grow.',
  avatarUrl: '/src/assets/images/avatar_ankit_1790498690280.jpg',
  coverUrl: '/src/assets/images/post_travel_deals_1790498725783.jpg',
  primaryColor: '#6366F1',
  secondaryColor: '#A855F7',
  font: 'Plus Jakarta Sans',
  mode: 'light',
  buttonStyle: 'rounded-xl',
  productLayout: 'grid',
  featuredProductIds: ['prod-1', 'prod-2', 'prod-3', 'prod-4'],
  socialLinks: {
    instagram: 'https://instagram.com/ankit_creates',
    tiktok: 'https://tiktok.com/@ankit_tech',
    whatsapp: 'https://wa.me/919876543210',
    telegram: 'https://t.me/AutoDM_AnkitBot',
    youtube: 'https://youtube.com/@ankit_creates',
    website: 'https://ankitsharma.me',
  },
};

export const INITIAL_CUSTOM_DOMAIN: CustomDomainConfig = {
  domain: 'shop.ankitsharma.me',
  status: 'connected',
  sslStatus: 'active',
  type: 'CNAME',
  name: 'shop',
  targetValue: 'domains.autodm.com',
  configuredAt: 'Apr 12, 2026',
};

// ==========================================
// MULTI-CHANNEL AUTOMATIONS (Visual Node Architecture)
// ==========================================

export const INITIAL_AUTOMATIONS: Automation[] = [
  {
    id: 'auto-ig-1',
    name: 'Instagram Accelerator Launch DM',
    channel: 'instagram',
    triggerType: 'instagram_comment',
    conditionType: 'keyword_contains',
    actionType: 'send_message',
    steps: [
      { id: 's1', type: 'trigger', title: 'Instagram Post Comment', channel: 'instagram', config: { postCode: '#cKcJ39' } },
      { id: 's2', type: 'condition', title: 'Keyword contains: COURSE or ACCELERATOR', config: { keywords: ['course', 'accelerator', 'blueprint'] } },
      { id: 's3', type: 'action', title: 'Send Automated Direct Message', channel: 'instagram', config: { template: 'Hey {{name}}! Here is your link.' } },
      { id: 's4', type: 'action', title: 'Attach Product Card & Code CREATOR10', config: { productId: 'prod-1' } },
    ],
    postId: 'post-101',
    postCode: '#cKcJ39',
    postThumbnail: '/src/assets/images/post_course_launch_1790498703738.jpg',
    postCaption: 'How I scaled my creator revenue to $25k/mo without ad spend. Comment COURSE for the blueprint!',
    keyword: 'course',
    keywords: ['course', 'accelerator', 'blueprint', 'masterclass'],
    replyMessage: "Hey {{username}}! 👋 Thanks for asking. Here is the direct link to the Creator Accelerator:\n{{product_link}}\n\nUse code CREATOR10 for 10% off at checkout today!",
    dmMessage: "Hey {{username}}! 👋 Thanks for asking. Here is the direct link to the Creator Accelerator:\n{{product_link}}\n\nUse code CREATOR10 for 10% off at checkout today!",
    targetProductId: 'prod-1',
    status: 'active',
    createdAt: 'Apr 20, 2026',
    triggerCount: 842,
    dmsSent: 820,
    clicks: 694,
    conversions: 142,
    conversionRevenue: 6958,
  },
  {
    id: 'auto-wa-1',
    name: 'WhatsApp Concierge Price Flow',
    channel: 'whatsapp',
    triggerType: 'whatsapp_incoming_message',
    conditionType: 'keyword_contains',
    actionType: 'send_product',
    steps: [
      { id: 's1', type: 'trigger', title: 'Inbound WhatsApp Message', channel: 'whatsapp', config: { target: 'all_contacts' } },
      { id: 's2', type: 'condition', title: 'Message contains: PRICE or BUY', config: { keywords: ['price', 'buy', 'catalog'] } },
      { id: 's3', type: 'action', title: 'Send Official WhatsApp Template', channel: 'whatsapp', config: { template: 'product_showcase_v1' } },
      { id: 's4', type: 'action', title: 'Route to Storefront Checkout with Instant Razorpay link', config: { productId: 'prod-2' } },
    ],
    keyword: 'price',
    keywords: ['price', 'buy', 'cost', 'quote'],
    replyMessage: "Hello! 👋 Thanks for reaching Ankit's studio concierge. Our Studio Pro Headphones are ₹7,499 ($89) with free courier shipping.\n\nTap below to order directly:\n{{product_link}}",
    dmMessage: "Hello! 👋 Thanks for reaching Ankit's studio concierge. Our Studio Pro Headphones are ₹7,499 ($89) with free courier shipping.\n\nTap below to order directly:\n{{product_link}}",
    targetProductId: 'prod-2',
    postCode: 'WA-MSG',
    postThumbnail: '/src/assets/images/post_product_headphones_1790498714259.jpg',
    status: 'active',
    createdAt: 'Apr 22, 2026',
    triggerCount: 418,
    dmsSent: 405,
    clicks: 312,
    conversions: 62,
    conversionRevenue: 5518,
  },
  {
    id: 'auto-tg-1',
    name: 'Telegram /buy Command & Catalog Bot',
    channel: 'telegram',
    triggerType: 'telegram_command',
    conditionType: 'message_contains',
    actionType: 'send_storefront_link',
    steps: [
      { id: 's1', type: 'trigger', title: 'Telegram Command: /buy or /start', channel: 'telegram', config: { command: '/buy' } },
      { id: 's2', type: 'condition', title: 'Check user Telegram identity in CRM', config: { autoRegister: true } },
      { id: 's3', type: 'action', title: 'Send Inline Telegram Storefront Card', channel: 'telegram', config: { inlineButton: 'Open WebApp Store' } },
    ],
    command: '/buy',
    keyword: 'buy',
    keywords: ['/buy', '/start', '/catalog'],
    replyMessage: "Welcome to @AutoDM_AnkitBot! 🛍️\n\nChoose from our official creator catalog. Instant digital downloads and physical gear shipped worldwide:\n{{product_link}}",
    dmMessage: "Welcome to @AutoDM_AnkitBot! 🛍️\n\nChoose from our official creator catalog. Instant digital downloads and physical gear shipped worldwide:\n{{product_link}}",
    targetProductId: 'prod-3',
    postCode: 'TG-BOT',
    postThumbnail: '/src/assets/images/digital_product_1790499336046.jpg',
    status: 'active',
    createdAt: 'Apr 24, 2026',
    triggerCount: 520,
    dmsSent: 508,
    clicks: 440,
    conversions: 110,
    conversionRevenue: 2090,
  },
  {
    id: 'auto-tt-1',
    name: 'TikTok Video Comment Keyword Trigger',
    channel: 'tiktok',
    triggerType: 'tiktok_comment',
    conditionType: 'keyword_contains',
    actionType: 'send_message',
    steps: [
      { id: 's1', type: 'trigger', title: 'TikTok Video Comment', channel: 'tiktok', config: { videoId: 'tiktok_v_982' } },
      { id: 's2', type: 'condition', title: 'Keyword contains: LINK or PLAYBOOK', config: { keywords: ['link', 'playbook', 'free'] } },
      { id: 's3', type: 'action', title: 'Send TikTok Supported Profile Direct Reply', channel: 'tiktok', config: {} },
    ],
    postCode: '#TT-982',
    postThumbnail: '/src/assets/images/post_travel_deals_1790498725783.jpg',
    postCaption: 'Secret TikTok organic funnel strategy. Comment LINK for the 42-page PDF playbook!',
    keyword: 'link',
    keywords: ['link', 'playbook', 'free'],
    replyMessage: "Hey! Saw your comment on TikTok. Grab the full 42-page social commerce guide right here:\n{{product_link}}",
    dmMessage: "Hey! Saw your comment on TikTok. Grab the full 42-page social commerce guide right here:\n{{product_link}}",
    targetProductId: 'prod-3',
    status: 'active',
    createdAt: 'Apr 25, 2026',
    triggerCount: 310,
    dmsSent: 295,
    clicks: 210,
    conversions: 45,
    conversionRevenue: 855,
  },
];

// ==========================================
// UNIFIED CUSTOMER CRM (Cross-Channel Identities)
// ==========================================

export const INITIAL_CUSTOMERS: Customer[] = [
  {
    id: 'cust-1',
    name: 'Sarah Jenkins',
    email: 'sarah.j@gmail.com',
    phone: '+91 98765 43210',
    avatarUrl: '/src/assets/images/avatar_sarah_1790499318738.jpg',
    source: 'Instagram',
    primaryChannel: 'instagram',
    instagramUsername: 'sarah_123',
    identities: [
      { id: 'id-1', channel: 'instagram', handle: '@sarah_123', isPrimary: true, verifiedAt: 'Apr 21, 2026' },
      { id: 'id-2', channel: 'whatsapp', handle: '+91 98765 43210', isPrimary: false, verifiedAt: 'Apr 22, 2026' },
      { id: 'id-3', channel: 'telegram', handle: '@sarah_j', isPrimary: false, verifiedAt: 'Apr 25, 2026' },
    ],
    interestedProducts: ['Creator Accelerator 2026', 'Social Commerce Playbook'],
    ordersCount: 2,
    totalSpent: 68,
    status: 'repeat',
    lastInteraction: '10 mins ago',
    createdAt: 'Apr 21, 2026',
    tags: ['VIP Creator', 'Cross-Platform', 'Course Student'],
    notes: 'Initially commented on Instagram Reel #cKcJ39, later asked questions on WhatsApp Concierge and converted twice.',
  },
  {
    id: 'cust-2',
    name: 'Theo Evans',
    email: 'theo@devlabs.io',
    phone: '+91 98112 23344',
    avatarUrl: '/src/assets/images/avatar_ankit_1790498690280.jpg',
    source: 'TikTok',
    primaryChannel: 'tiktok',
    instagramUsername: 'theo.codes',
    identities: [
      { id: 'id-4', channel: 'tiktok', handle: '@theo.codes', isPrimary: true, verifiedAt: 'Apr 23, 2026' },
      { id: 'id-5', channel: 'whatsapp', handle: '+91 98112 23344', isPrimary: false, verifiedAt: 'Apr 24, 2026' },
    ],
    interestedProducts: ['Acoustic Studio Pro Wireless Headphones'],
    ordersCount: 1,
    totalSpent: 89,
    status: 'purchased',
    lastInteraction: '2 hours ago',
    createdAt: 'Apr 23, 2026',
    tags: ['Hardware Buyer', 'TikTok Lead'],
    notes: 'Discovered product via TikTok video. Confirmed courier tracking via WhatsApp concierge.',
  },
  {
    id: 'cust-3',
    name: 'Maya Kapoor',
    email: 'mayak@fashionstudio.com',
    phone: '+91 97234 56789',
    avatarUrl: '/src/assets/images/avatar_sarah_1790499318738.jpg',
    source: 'Instagram',
    primaryChannel: 'instagram',
    instagramUsername: 'maya.k',
    identities: [
      { id: 'id-6', channel: 'instagram', handle: '@maya.k', isPrimary: true, verifiedAt: 'Apr 25, 2026' },
      { id: 'id-7', channel: 'telegram', handle: '@mayakapoor', isPrimary: false, verifiedAt: 'Apr 26, 2026' },
    ],
    interestedProducts: ['1-on-1 Multi-Channel Funnel Audit & Setup'],
    ordersCount: 1,
    totalSpent: 99,
    status: 'purchased',
    lastInteraction: 'Yesterday',
    createdAt: 'Apr 25, 2026',
    tags: ['Coaching Client', 'High Ticket'],
    notes: 'Booked consulting slot. Telegram bot sent her calendar invitation and prep Notion board.',
  },
  {
    id: 'cust-4',
    name: 'Alex Rivera',
    email: 'alex@creatorcollective.net',
    phone: '+91 96543 21098',
    avatarUrl: '/src/assets/images/avatar_ankit_1790498690280.jpg',
    source: 'WhatsApp',
    primaryChannel: 'whatsapp',
    instagramUsername: 'alex_creates',
    identities: [
      { id: 'id-8', channel: 'whatsapp', handle: '+91 96543 21098', isPrimary: true, verifiedAt: 'Apr 27, 2026' },
      { id: 'id-9', channel: 'tiktok', handle: '@alex_creates', isPrimary: false, verifiedAt: 'Apr 27, 2026' },
    ],
    interestedProducts: ['Creator Accelerator 2026'],
    ordersCount: 0,
    totalSpent: 0,
    status: 'checkout',
    lastInteraction: '35 mins ago',
    createdAt: 'Apr 27, 2026',
    tags: ['Abandoned Checkout', 'High Value Lead'],
    notes: 'Initiated checkout on Razorpay via WhatsApp link. AutoDM follow-up sequence active.',
  },
  {
    id: 'cust-5',
    name: 'Vikram Malhotra',
    email: 'vikram@fintechpulse.in',
    phone: '+91 99887 76655',
    avatarUrl: '/src/assets/images/avatar_ankit_1790498690280.jpg',
    source: 'Telegram',
    primaryChannel: 'telegram',
    instagramUsername: 'vikram_m',
    identities: [
      { id: 'id-10', channel: 'telegram', handle: '@vikram_m', isPrimary: true, verifiedAt: 'Apr 26, 2026' },
      { id: 'id-11', channel: 'whatsapp', handle: '+91 99887 76655', isPrimary: false, verifiedAt: 'Apr 26, 2026' },
    ],
    interestedProducts: ['42-Page Social Commerce Playbook'],
    ordersCount: 1,
    totalSpent: 19,
    status: 'purchased',
    lastInteraction: '4 hours ago',
    createdAt: 'Apr 26, 2026',
    tags: ['Telegram VIP', 'Digital Buyer'],
    notes: 'Triggered /buy command in Telegram bot. Purchased PDF playbook within 90 seconds.',
  },
];

// ==========================================
// UNIFIED INBOX CONVERSATIONS (All Channels in One Place)
// ==========================================

export const INITIAL_CONVERSATIONS: Conversation[] = [
  {
    id: 'conv-ig-1',
    customerId: 'cust-1',
    customerName: 'Sarah Jenkins',
    channel: 'instagram',
    channelHandle: '@sarah_123',
    instagramUsername: 'sarah_123',
    avatarUrl: '/src/assets/images/avatar_sarah_1790499318738.jpg',
    lastMessage: 'Thank you Ankit! Just enrolled in the Accelerator course.',
    lastMessageTime: '10m ago',
    unreadCount: 0,
    status: 'open',
    assignedStatus: 'assigned',
    tags: ['Enrolled', 'VIP', 'Instagram'],
    messages: [
      { id: 'm-1', sender: 'customer', text: 'Where can I get this course? Commented COURSE on your reel.', timestamp: '2:40 PM', channel: 'instagram' },
      {
        id: 'm-2',
        sender: 'system_bot',
        text: "Hey @sarah_123! 👋 Here's the direct link to the Creator Accelerator:\nhttps://shop.ankitsharma.me/p/creator-accelerator",
        timestamp: '2:40 PM',
        channel: 'instagram',
        productCard: {
          title: 'Instagram & TikTok Creator Accelerator 2026',
          price: 49,
          image: '/src/assets/images/post_course_launch_1790498703738.jpg',
          link: 'https://shop.ankitsharma.me/p/creator-accelerator',
        },
      },
      { id: 'm-3', sender: 'customer', text: 'Is the private Discord included?', timestamp: '2:42 PM', channel: 'instagram' },
      { id: 'm-4', sender: 'creator', text: 'Yes absolutely Sarah! You get lifetime access to our lounge and weekly audits.', timestamp: '2:44 PM', channel: 'instagram' },
      { id: 'm-5', sender: 'customer', text: 'Thank you Ankit! Just enrolled in the Accelerator course.', timestamp: '2:46 PM', channel: 'instagram' },
    ],
  },
  {
    id: 'conv-wa-1',
    customerId: 'cust-2',
    customerName: 'Theo Evans',
    channel: 'whatsapp',
    channelHandle: '+91 98112 23344',
    instagramUsername: 'theo.codes',
    avatarUrl: '/src/assets/images/avatar_ankit_1790498690280.jpg',
    lastMessage: 'Great, thanks for the Delhivery tracking number!',
    lastMessageTime: '1h ago',
    unreadCount: 0,
    status: 'open',
    assignedStatus: 'bot_handling',
    tags: ['WhatsApp', 'Hardware', 'Order Shipped'],
    messages: [
      { id: 'mw-1', sender: 'customer', text: 'Hi Ankit, saw your studio headphones on TikTok. Can I pay via Cashfree or UPI?', timestamp: '11:15 AM', channel: 'whatsapp' },
      {
        id: 'mw-2',
        sender: 'system_bot',
        text: "Hi Theo! 👋 Yes, both Cashfree UPI & Cards are supported directly on our storefront:\nhttps://shop.ankitsharma.me/p/acoustic-studio-pro-headphones",
        timestamp: '11:15 AM',
        channel: 'whatsapp',
        productCard: {
          title: 'Acoustic Studio Pro Wireless Headphones',
          price: 89,
          image: '/src/assets/images/post_product_headphones_1790498714259.jpg',
          link: 'https://shop.ankitsharma.me/p/acoustic-studio-pro-headphones',
        },
      },
      { id: 'mw-3', sender: 'customer', text: 'Order placed! Here is the order confirmation #ORD-8491.', timestamp: '11:22 AM', channel: 'whatsapp' },
      { id: 'mw-4', sender: 'creator', text: 'Order received Theo! Dispatching via Delhivery Air this afternoon. Tracking: DLV9481920.', timestamp: '11:30 AM', channel: 'whatsapp' },
      { id: 'mw-5', sender: 'customer', text: 'Great, thanks for the Delhivery tracking number!', timestamp: '11:32 AM', channel: 'whatsapp' },
    ],
  },
  {
    id: 'conv-tg-1',
    customerId: 'cust-5',
    customerName: 'Vikram Malhotra',
    channel: 'telegram',
    channelHandle: '@vikram_m',
    instagramUsername: 'vikram_m',
    avatarUrl: '/src/assets/images/avatar_ankit_1790498690280.jpg',
    lastMessage: 'Awesome bot! The PDF playbook downloaded automatically.',
    lastMessageTime: '3h ago',
    unreadCount: 0,
    status: 'closed',
    assignedStatus: 'bot_handling',
    tags: ['Telegram Bot', 'Digital Asset'],
    messages: [
      { id: 'mt-1', sender: 'customer', text: '/buy', timestamp: '9:00 AM', channel: 'telegram' },
      {
        id: 'mt-2',
        sender: 'system_bot',
        text: "Welcome to AutoDM Store Bot! Here is our 42-page Social Commerce Playbook:\nhttps://shop.ankitsharma.me/p/social-commerce-playbook",
        timestamp: '9:00 AM',
        channel: 'telegram',
        productCard: {
          title: '42-Page Multi-Channel Social Commerce Playbook',
          price: 19,
          image: '/src/assets/images/digital_product_1790499336046.jpg',
          link: 'https://shop.ankitsharma.me/p/social-commerce-playbook',
        },
      },
      { id: 'mt-3', sender: 'customer', text: 'Awesome bot! The PDF playbook downloaded automatically.', timestamp: '9:05 AM', channel: 'telegram' },
    ],
  },
  {
    id: 'conv-tt-1',
    customerId: 'cust-4',
    customerName: 'Alex Rivera',
    channel: 'tiktok',
    channelHandle: '@alex_creates',
    instagramUsername: 'alex_creates',
    avatarUrl: '/src/assets/images/avatar_ankit_1790498690280.jpg',
    lastMessage: 'Will check out the discount code today.',
    lastMessageTime: '45m ago',
    unreadCount: 1,
    status: 'open',
    assignedStatus: 'escalated',
    tags: ['TikTok', 'Lead', 'Follow-up'],
    messages: [
      { id: 'mtt-1', sender: 'customer', text: 'Hey Ankit, left a comment on your viral TikTok about creator funnels.', timestamp: '1:45 PM', channel: 'tiktok' },
      {
        id: 'mtt-2',
        sender: 'system_bot',
        text: "Hey Alex! Thanks for reaching out. Here is our direct storefront link:\nhttps://shop.ankitsharma.me",
        timestamp: '1:45 PM',
        channel: 'tiktok',
      },
      { id: 'mtt-3', sender: 'customer', text: 'Will check out the discount code today.', timestamp: '1:50 PM', channel: 'tiktok' },
    ],
  },
];

// ==========================================
// STOREFRONT ORDERS (With Channel Attribution)
// ==========================================

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'ord-8492',
    orderNumber: '#ORD-8492',
    customerId: 'cust-1',
    customerName: 'Sarah Jenkins',
    customerEmail: 'sarah.j@gmail.com',
    channel: 'instagram',
    channelHandle: '@sarah_123',
    instagramUsername: 'sarah_123',
    items: [
      {
        productId: 'prod-1',
        title: 'Instagram & TikTok Creator Accelerator 2026',
        type: 'digital',
        price: 49,
        quantity: 1,
        image: '/src/assets/images/post_course_launch_1790498703738.jpg',
      },
    ],
    subtotal: 49,
    shipping: 0,
    total: 49,
    paymentGateway: 'Razorpay',
    paymentId: 'pay_Lp83Kn92a',
    paymentStatus: 'paid',
    orderStatus: 'delivered',
    createdAt: 'Today, 2:46 PM',
  },
  {
    id: 'ord-8491',
    orderNumber: '#ORD-8491',
    customerId: 'cust-2',
    customerName: 'Theo Evans',
    customerEmail: 'theo@devlabs.io',
    channel: 'tiktok',
    channelHandle: '@theo.codes',
    instagramUsername: 'theo.codes',
    items: [
      {
        productId: 'prod-2',
        title: 'Acoustic Studio Pro Wireless Headphones',
        type: 'physical',
        price: 89,
        quantity: 1,
        variantName: 'Matte Obsidian',
        image: '/src/assets/images/post_product_headphones_1790498714259.jpg',
      },
    ],
    subtotal: 89,
    shipping: 0,
    total: 89,
    paymentGateway: 'Cashfree',
    paymentId: 'cf_ord_938104',
    paymentStatus: 'paid',
    orderStatus: 'shipped',
    createdAt: 'Today, 11:22 AM',
    shippingAddress: {
      address: 'Flat 402, Green Glen Layout, Bellandur',
      city: 'Bengaluru',
      state: 'Karnataka',
      postalCode: '560103',
    },
  },
  {
    id: 'ord-8490',
    orderNumber: '#ORD-8490',
    customerId: 'cust-3',
    customerName: 'Maya Kapoor',
    customerEmail: 'mayak@fashionstudio.com',
    channel: 'whatsapp',
    channelHandle: '+91 97234 56789',
    instagramUsername: 'maya.k',
    items: [
      {
        productId: 'prod-4',
        title: '1-on-1 Multi-Channel Funnel Audit & Setup',
        type: 'service',
        price: 99,
        quantity: 1,
        image: '/src/assets/images/avatar_ankit_1790498690280.jpg',
      },
    ],
    subtotal: 99,
    shipping: 0,
    total: 99,
    paymentGateway: 'Razorpay',
    paymentId: 'pay_Kq92Lp01a',
    paymentStatus: 'paid',
    orderStatus: 'processing',
    createdAt: 'Yesterday, 4:15 PM',
  },
  {
    id: 'ord-8489',
    orderNumber: '#ORD-8489',
    customerId: 'cust-5',
    customerName: 'Vikram Malhotra',
    customerEmail: 'vikram@fintechpulse.in',
    channel: 'telegram',
    channelHandle: '@vikram_m',
    instagramUsername: 'vikram_m',
    items: [
      {
        productId: 'prod-3',
        title: '42-Page Multi-Channel Social Commerce Playbook',
        type: 'digital',
        price: 19,
        quantity: 1,
        image: '/src/assets/images/digital_product_1790499336046.jpg',
      },
    ],
    subtotal: 19,
    shipping: 0,
    total: 19,
    paymentGateway: 'Razorpay',
    paymentId: 'pay_Jp71Mn03b',
    paymentStatus: 'paid',
    orderStatus: 'delivered',
    createdAt: '2 days ago',
  },
];

// ==========================================
// CHANNEL ATTRIBUTION & REVENUE ANALYTICS
// ==========================================

export const CHANNEL_ANALYTICS: ChannelAnalyticsData[] = [
  {
    channel: 'instagram',
    name: 'Instagram',
    color: '#E1306C',
    iconBg: 'from-amber-400 via-pink-500 to-purple-600',
    messages: 1842,
    engagement: 4210,
    leads: 680,
    productClicks: 1420,
    storeVisits: 3840,
    orders: 218,
    revenue: 25000,
  },
  {
    channel: 'tiktok',
    name: 'TikTok',
    color: '#00F2FE',
    iconBg: 'from-cyan-400 via-black to-pink-500',
    messages: 950,
    engagement: 3100,
    leads: 420,
    productClicks: 980,
    storeVisits: 2450,
    orders: 142,
    revenue: 12000,
  },
  {
    channel: 'whatsapp',
    name: 'WhatsApp',
    color: '#25D366',
    iconBg: 'from-emerald-500 to-green-600',
    messages: 620,
    engagement: 1420,
    leads: 310,
    productClicks: 590,
    storeVisits: 1240,
    orders: 94,
    revenue: 8000,
  },
  {
    channel: 'telegram',
    name: 'Telegram',
    color: '#229ED9',
    iconBg: 'from-sky-400 to-blue-600',
    messages: 480,
    engagement: 980,
    leads: 210,
    productClicks: 420,
    storeVisits: 840,
    orders: 51,
    revenue: 5000,
  },
];

export const INITIAL_PAYMENT_CONFIGS: PaymentGatewayConfig[] = [
  {
    provider: 'Razorpay',
    isConnected: true,
    merchantId: 'rzp_live_merch_849201',
    keyId: 'rzp_live_9482710398',
    webhookSecretSet: true,
    webhookUrl: 'https://api.autodm.com/webhooks/razorpay/v1',
    currency: 'INR / USD',
    mode: 'live',
    connectedAt: 'Connected on Jan 14, 2026',
  },
  {
    provider: 'Cashfree',
    isConnected: true,
    merchantId: 'cf_app_991823',
    keyId: 'cf_live_key_94810284',
    webhookSecretSet: true,
    webhookUrl: 'https://api.autodm.com/webhooks/cashfree/v1',
    currency: 'INR',
    mode: 'live',
    connectedAt: 'Connected on Feb 02, 2026',
  },
];

export const INITIAL_ACCOUNT = INITIAL_INSTAGRAM_ACCOUNT;

export const INITIAL_ACTIVITIES: ActivityItem[] = [
  {
    id: 'act-1',
    type: 'comment_matched',
    channel: 'instagram',
    title: 'Instagram comment matched',
    subtitle: '“course please”',
    context: 'on Reel #cKcJ39',
    timeAgo: '2m ago',
    userHandle: '@sarah_123',
  },
  {
    id: 'act-2',
    type: 'dm_sent',
    channel: 'whatsapp',
    title: 'WhatsApp Concierge reply sent',
    subtitle: '“Here’s the Studio Headphones link...”',
    context: '+91 98112 23344',
    timeAgo: '5m ago',
    userHandle: '+91 98112 23344',
  },
  {
    id: 'act-3',
    type: 'comment_matched',
    channel: 'telegram',
    title: 'Telegram /buy command triggered',
    subtitle: '“Delivered Playbook PDF link”',
    context: '@AutoDM_AnkitBot',
    timeAgo: '12m ago',
    userHandle: '@vikram_m',
  },
  {
    id: 'act-4',
    type: 'dm_sent',
    channel: 'tiktok',
    title: 'TikTok interaction response sent',
    subtitle: '“Check out our store...”',
    context: 'Video #TT-982',
    timeAgo: '18m ago',
    userHandle: '@alex_creates',
  },
  {
    id: 'act-5',
    type: 'order_placed',
    channel: 'instagram',
    title: 'New Order #ORD-8492',
    subtitle: 'Sarah Jenkins paid $49 via Razorpay',
    context: 'Storefront Direct',
    timeAgo: '24m ago',
    userHandle: '@sarah_123',
    amount: 49,
  },
];

export const TOP_KEYWORDS: KeywordMetric[] = [
  { keyword: 'course', percentage: 28, count: 482, revenue: 10682, rank: 1, color: '#6366F1' },
  { keyword: 'price', percentage: 22, count: 390, revenue: 7476, rank: 2, color: '#25D366' },
  { keyword: 'buy', percentage: 18, count: 310, revenue: 5518, rank: 3, color: '#229ED9' },
  { keyword: 'link', percentage: 15, count: 258, revenue: 3135, rank: 4, color: '#00F2FE' },
  { keyword: 'details', percentage: 9, count: 154, revenue: 3762, rank: 5, color: '#E1306C' },
  { keyword: 'catalog', percentage: 8, count: 138, revenue: 2090, rank: 6, color: '#A855F7' },
];

export const PERFORMANCE_DATA: PerformanceSlice[] = [
  { label: 'Instagram (42%)', percentage: 42, color: '#E1306C', count: 564 },
  { label: 'TikTok (24%)', percentage: 24, color: '#00F2FE', count: 322 },
  { label: 'WhatsApp (20%)', percentage: 20, color: '#25D366', count: 268 },
  { label: 'Telegram (14%)', percentage: 14, color: '#229ED9', count: 188 },
];

export const DMS_OVERVIEW_7D: DailyDMData[] = [
  { date: 'Apr 21', value: 124, dmsSent: 124, comments: 240 },
  { date: 'Apr 22', value: 146, dmsSent: 146, comments: 285 },
  { date: 'Apr 23', value: 168, dmsSent: 168, comments: 310 },
  { date: 'Apr 24', value: 152, dmsSent: 152, comments: 290 },
  { date: 'Apr 25', value: 195, dmsSent: 195, comments: 380 },
  { date: 'Apr 26', value: 215, dmsSent: 215, comments: 412 },
  { date: 'Apr 27', value: 242, dmsSent: 242, comments: 468 },
];

export const DMS_OVERVIEW_30D: DailyDMData[] = [
  { date: 'Apr 01', value: 75, dmsSent: 75 },
  { date: 'Apr 05', value: 110, dmsSent: 110 },
  { date: 'Apr 10', value: 140, dmsSent: 140 },
  { date: 'Apr 15', value: 175, dmsSent: 175 },
  { date: 'Apr 20', value: 195, dmsSent: 195 },
  { date: 'Apr 25', value: 220, dmsSent: 220 },
  { date: 'Apr 27', value: 242, dmsSent: 242 },
];

export const DMS_OVERVIEW_90D: DailyDMData[] = [
  { date: 'Feb', value: 1420, dmsSent: 1420 },
  { date: 'Mar', value: 2890, dmsSent: 2890 },
  { date: 'Apr', value: 4850, dmsSent: 4850 },
];

export const RECENT_LOGS: LogEntry[] = [
  {
    id: 'log-1',
    timestamp: 'Today, 2:48:12 PM',
    level: 'SUCCESS',
    channel: 'instagram',
    event: 'INSTAGRAM_DM_DISPATCHED',
    userHandle: '@sarah_123',
    postCode: '#cKcJ39',
    details: 'Keyword "course" detected in comment. Auto-sent DM with Accelerator checkout link.',
    latencyMs: 142,
  },
  {
    id: 'log-2',
    timestamp: 'Today, 2:40:05 PM',
    level: 'SUCCESS',
    channel: 'whatsapp',
    event: 'WHATSAPP_TEMPLATE_SENT',
    userHandle: '+91 98112 23344',
    postCode: 'WA-MSG',
    details: 'Incoming WhatsApp query "price" verified. Automated product showcase message delivered.',
    latencyMs: 95,
  },
  {
    id: 'log-3',
    timestamp: 'Today, 1:15:42 PM',
    level: 'SUCCESS',
    channel: 'telegram',
    event: 'TELEGRAM_COMMAND_PROCESSED',
    userHandle: '@vikram_m',
    postCode: 'TG-BOT',
    details: 'Command /buy parsed. Instant inline keyboard with digital playbook sent.',
    latencyMs: 64,
  },
  {
    id: 'log-4',
    timestamp: 'Today, 11:22:19 AM',
    level: 'INFO',
    channel: 'tiktok',
    event: 'TIKTOK_COMMENT_FILTERED',
    userHandle: '@alex_creates',
    postCode: '#TT-982',
    details: 'Comment webhook received. Verified capability compliance.',
    latencyMs: 180,
  },
];
